version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nest-api:prod
    container_name: nest-api
    env_file:
      - ./.env 
    restart: unless-stopped
